// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MplDbApi.Data;

#nullable disable

namespace MplDbApi.Migrations.BMplbase
{
    [DbContext(typeof(BMplbaseContext))]
    [Migration("20260330_InitialSchema")]
    partial class InitialSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasPostgresExtension("pgcrypto");

            modelBuilder.Entity("MplDbApi.Models.DeliveryType", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("delivery_type_pk");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("delivery_type_unique");

                    b.ToTable("delivery_type", (string)null);
                });

            modelBuilder.Entity("MplDbApi.Models.Material", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("material_pk");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("material_name_uindex");

                    b.ToTable("material", (string)null);
                });

            modelBuilder.Entity("MplDbApi.Models.MaterialGroup", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("material_group_pk");

                    b.ToTable("material_group", (string)null);
                });

            modelBuilder.Entity("MplDbApi.Models.MaterialProperty", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<int>("Uid")
                        .HasColumnType("integer")
                        .HasColumnName("uid");

                    b.HasKey("Id")
                        .HasName("material_property_pk");

                    b.HasIndex("Uid", "PropertyId")
                        .IsUnique()
                        .HasName("material_property_uid_property_id_key");

                    b.HasIndex("PropertyId");

                    b.ToTable("material_property", (string)null);

                    b.HasOne("MplDbApi.Models.Property", "Property")
                        .WithMany("MaterialProperties")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("material_property_property_fk");

                    b.HasOne("MplDbApi.Models.MaterialSource", "UidNavigation")
                        .WithMany("MaterialProperties")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("material_property_uid_fk");

                    b.Navigation("Property");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("MplDbApi.Models.MaterialSource", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<int>("DeliveryTypeId")
                        .HasColumnType("integer")
                        .HasColumnName("delivery_type_id");

                    b.Property<int>("MaterialGroupId")
                        .HasColumnType("integer")
                        .HasColumnName("material_group_id");

                    b.Property<int>("MaterialId")
                        .HasColumnType("integer")
                        .HasColumnName("material_id");

                    b.Property<int>("SourceId")
                        .HasColumnType("integer")
                        .HasColumnName("source_id");

                    b.Property<string>("TargetMarket")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("target_market");

                    b.Property<int>("Uid")
                        .HasColumnType("integer")
                        .HasColumnName("uid");

                    b.Property<int>("UnitId")
                        .HasColumnType("integer")
                        .HasColumnName("unit_id");

                    b.HasKey("Id")
                        .HasName("material_source_pk");

                    b.HasIndex("Uid")
                        .IsUnique()
                        .HasName("material_source_uid_key");

                    b.HasIndex("MaterialId", "SourceId", "TargetMarket", "UnitId", "DeliveryTypeId", "MaterialGroupId")
                        .IsUnique()
                        .HasName("material_source_material_id_source_id_target_market_unit_de_key");

                    b.HasIndex("DeliveryTypeId");

                    b.HasIndex("MaterialGroupId");

                    b.HasIndex("SourceId");

                    b.HasIndex("UnitId");

                    b.ToTable("material_source", (string)null);

                    b.HasOne("MplDbApi.Models.DeliveryType", "DeliveryType")
                        .WithMany("MaterialSources")
                        .HasForeignKey("DeliveryTypeId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("material_source_delivery_type_id_fk");

                    b.HasOne("MplDbApi.Models.Material", "Material")
                        .WithMany("MaterialSources")
                        .HasForeignKey("MaterialId")
                        .HasConstraintName("material_source_material_fk");

                    b.HasOne("MplDbApi.Models.MaterialGroup", "MaterialGroup")
                        .WithMany("MaterialSources")
                        .HasForeignKey("MaterialGroupId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("material_source_material_group_id_fk");

                    b.HasOne("MplDbApi.Models.Source", "Source")
                        .WithMany("MaterialSources")
                        .HasForeignKey("SourceId")
                        .HasConstraintName("material_source_source_fk");

                    b.HasOne("MplDbApi.Models.Unit", "Unit")
                        .WithMany("MaterialSources")
                        .HasForeignKey("UnitId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("material_source_unit_id_fk");

                    b.Navigation("DeliveryType");

                    b.Navigation("Material");

                    b.Navigation("MaterialGroup");

                    b.Navigation("Source");

                    b.Navigation("Unit");
                });

            modelBuilder.Entity("MplDbApi.Models.MaterialValue", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<DateOnly>("CreatedOn")
                        .HasColumnType("date")
                        .HasColumnName("created_on");

                    b.Property<DateTime?>("LastUpdated")
                        .HasColumnType("timestamp without time zone")
                        .HasColumnName("last_updated");

                    b.Property<int>("PropertyId")
                        .HasColumnType("integer")
                        .HasColumnName("property_id");

                    b.Property<int>("Uid")
                        .HasColumnType("integer")
                        .HasColumnName("uid");

                    b.Property<decimal?>("ValueDecimal")
                        .HasColumnType("numeric")
                        .HasColumnName("value_decimal");

                    b.Property<string>("ValueStr")
                        .HasColumnType("character varying")
                        .HasColumnName("value_str");

                    b.HasKey("Id")
                        .HasName("material_value_pk");

                    b.HasIndex("Id")
                        .IsUnique()
                        .HasName("material_value_id_uindex");

                    b.HasIndex("Uid", "PropertyId", "CreatedOn")
                        .IsUnique()
                        .HasName("material_value_all_together_uindex");

                    b.HasIndex("PropertyId");

                    b.ToTable("material_value", (string)null);

                    b.HasOne("MplDbApi.Models.Property", "Property")
                        .WithMany("MaterialValues")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("material_value_property_fk");

                    b.HasOne("MplDbApi.Models.MaterialSource", "UidNavigation")
                        .WithMany("MaterialValues")
                        .HasForeignKey("Uid")
                        .OnDelete(DeleteBehavior.ClientSetNull)
                        .HasConstraintName("material_value_material_source_fk");

                    b.Navigation("Property");

                    b.Navigation("UidNavigation");
                });

            modelBuilder.Entity("MplDbApi.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("property_pk");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("property_name_uindex");

                    b.ToTable("property", (string)null);
                });

            modelBuilder.Entity("MplDbApi.Models.Source", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Kind")
                        .HasColumnType("character varying")
                        .HasColumnName("kind");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.Property<string>("Url")
                        .HasColumnType("character varying")
                        .HasColumnName("url");

                    b.HasKey("Id")
                        .HasName("source_pk");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("source_name_uindex");

                    b.ToTable("source", (string)null);
                });

            modelBuilder.Entity("MplDbApi.Models.Unit", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("unit_pk");

                    b.HasIndex("Name")
                        .IsUnique()
                        .HasName("unit_name_unique");

                    b.ToTable("unit", (string)null);
                });

            modelBuilder.Entity("MplDbApi.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("password");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("username");

                    b.HasKey("Id")
                        .HasName("user_pk");

                    b.HasIndex("Username")
                        .IsUnique()
                        .HasName("user_username_key");

                    b.ToTable("user", (string)null);
                });

            modelBuilder.Entity("MplDbApi.Models.DeliveryType", b =>
                {
                    b.Navigation("MaterialSources");
                });

            modelBuilder.Entity("MplDbApi.Models.Material", b =>
                {
                    b.Navigation("MaterialSources");
                });

            modelBuilder.Entity("MplDbApi.Models.MaterialGroup", b =>
                {
                    b.Navigation("MaterialSources");
                });

            modelBuilder.Entity("MplDbApi.Models.MaterialSource", b =>
                {
                    b.Navigation("MaterialProperties");

                    b.Navigation("MaterialValues");
                });

            modelBuilder.Entity("MplDbApi.Models.Property", b =>
                {
                    b.Navigation("MaterialProperties");

                    b.Navigation("MaterialValues");
                });

            modelBuilder.Entity("MplDbApi.Models.Source", b =>
                {
                    b.Navigation("MaterialSources");
                });

            modelBuilder.Entity("MplDbApi.Models.Unit", b =>
                {
                    b.Navigation("MaterialSources");
                });
#pragma warning restore 612, 618
        }
    }
}
