// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MplDbApi.Data;

#nullable disable

namespace MplDbApi.Migrations
{
    [DbContext(typeof(FilterContext))]
    partial class FilterContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.3");

            modelBuilder.Entity("MplDbApi.Models.Filters.DataFilter", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("AffectedRole")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Groups")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("MaterialIds")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Properties")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Sources")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("Units")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Filters");
                });
#pragma warning restore 612, 618
        }
    }
}
